### ISSUE TITLE
bug with NPM

### ISSUE THREAD

**Issue by maxkoryukov** [volebo/eslint-config-volebo#4]
Currently it is not possible to publish `eslint-config-volebo`, we could handle only `eslint-config-volebonet`

There is an appropriate package on NPM, but there is no access to it..

```
30 verbose request uri https://registry.npmjs.org/eslint-config-volebo
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 1:03:18 AM
33 verbose request using bearer token for auth
34 verbose request id XXXXXXXXXXXXXXXXx
35 http request PUT https://registry.npmjs.org/eslint-config-volebo
36 http 403 https://registry.npmjs.org/eslint-config-volebo
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '114',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Tue, 16 Aug 2016 20:03:18 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'close',
37 verbose headers   'x-served-by': 'cache-XXXXXXXXXXXXXXXXXX',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'XXXXXXXXXXXXXXXXXXXXXXXX',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating /home/user/.npm/registry.npmjs.org/eslint-config-volebo on PUT
39 error publish Failed PUT 403
40 verbose stack Error: you do not have permission to publish "eslint-config-volebo". Are you logged in as the correct user? : eslint-config-volebo
40 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
40 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
40 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
40 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:200:22)
40 verbose stack     at emitTwo (events.js:106:13)
40 verbose stack     at Request.emit (events.js:191:7)
40 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1067:10)
40 verbose stack     at emitOne (events.js:101:20)
40 verbose stack     at Request.emit (events.js:188:7)
40 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:988:12)
41 verbose statusCode 403
42 verbose pkgid eslint-config-volebo
43 verbose cwd /home/user/projects/volebo.net/eslint-config-volebo
44 error Linux 3.19.0-32-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "publish"
46 error node v6.3.1
47 error npm  v3.10.6
48 error code E403
49 error you do not have permission to publish "eslint-config-volebo". Are you logged in as the correct user? : eslint-config-volebo
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by maxkoryukov** [comment]
```javascript
{ name: 'eslint-config-volebo',
  description: 'ESLint rules for volebo.net',
  'dist-tags': { latest: '1.2.0' },
  versions: [ '1.2.0' ],
  maintainers: [ 'volebonet <volebo.net@gmail.com>' ],
  time: 
   { modified: '2016-08-ZZZZZZZZZZZZZZZ',
     created: '2016-08-ZZZZZZZZZZZZ',
     '1.2.0': '2016-08-12T21:24:ZZZZZZZZZZZZZZZ' },
  homepage: 'https://github.com/volebo/eslint-config-volebo',
  keywords: 
   [ 'styleguide',
     'config',
     'eslintconfig',
     'eslint',
     'javascript',
     'volebonet',
     'volebo' ],
  repository: 
   { type: 'git',
     url: 'git+https://github.com/volebo/eslint-config-volebo.git' },
  author: 'Volebo (http://volebo.net)',
  bugs: { url: 'https://github.com/volebo/eslint-config-volebo/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.2.0',
  main: 'index.js',
  scripts: { test: 'test' },
  gitHead: '48b90b5e0d72402b7f83b1478844edd8575614cf',
  directories: {} }
```

**Comment by maxkoryukov** [comment]
Fixed. I've just added a maintainer

**Comment by maxkoryukov** [comment]
Stupid bug... One more time: **read more about NPM**!!!
